### ISSUE TITLE
failing build with recent GCC (11.3.0)

### ISSUE THREAD

**Issue by boegel** [joachimwolff/minHashNearestNeighbors#10]
I'm running into compilation failures with a recent version of GCC:

```
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -I/software/FFTW/3.3.10-GCC-11.3.0/include -I/software/FlexiBLAS/3.2.0-GCC-11.3.0/include -I/software/FlexiBLAS/3.2.0-GCC-11.3.0/include/flexiblas -fPIC -DOPENMP -I/software/Python/3.10.4-GCCcore-11.3.0/include/python3.10 -c sparse_neighbors_search/computation/inverseIndexStorageUnorderedMap.cpp -o build/temp.linux-x86_64-cpython-310/sparse_neighbors_search/computation/inverseIndexStorageUnorderedMap.o -fopenmp -O3 -std=c++11 -funroll-loops -msse4.1
  In file included from sparse_neighbors_search/computation/typeDefinitions.h:19,
                   from sparse_neighbors_search/computation/inverseIndexStorage.h:15,
                   from sparse_neighbors_search/computation/inverseIndexStorageUnorderedMap.h:15,
                   from sparse_neighbors_search/computation/inverseIndexStorageUnorderedMap.cpp:16:
  sparse_neighbors_search/computation/typeDefinitionsBasic.h:27:22: error: size_t was not declared in this scope; did you mean std::size_t?
     27 | typedef std::vector< size_t > vsize_t;
        |                      ^~~~~~
        |                      std::size_t
```

Is this a known issue? Any fixes available for it?

**Comment by boegel** [comment]
fixed with the change proposed in #11
